# Generated by Django 4.2.4 on 2023-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_alter_studenttable_course_id_usertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.DateField(),
        ),
    ]
